# Secret is now defined in config/secrets.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-orders
  labels:
    app: postgres-orders
spec:
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
  selector:
    app: postgres-orders
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-orders
spec:
  serviceName: postgres-orders
  replicas: 1
  selector:
    matchLabels:
      app: postgres-orders
  template:
    metadata:
      labels:
        app: postgres-orders
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
        - secretRef:
            name: postgres-secrets
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-orders-data-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-orders-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
