apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
type: Opaque
stringData:
  SUPABASE_URL: "https://ccqjdxlwtrljcudvulsa.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcWpkeGx3dHJsamN1ZHZ1bHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NzkzMTgsImV4cCI6MjA3MzI1NTMxOH0.ZnVnF4RYFncwGW4C4Ta7u5Ha7WscaVFRmaSOHe7PruA"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "orders_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "example"